name: Checks

on:
  push
  pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
        run: yarn install
        run: yarn lint
    test: 
      name: Test
      runs-on: ubuntu-latest

      steps:
          uses: actions/checkout@v2
          uses: actions/setup-node@v2
          with:
            node-version: 16
            registry-url: https://registry.npmjs.org
          run: yarn install
          run: yarn test